version: '2'
services:
  h2:
    container_name: 'h2'
    hostname: 'h2'
    image: 1000kit/h2
    ports:
      - "8181:8181"
      - "1521:1521"
#    volumes:
#      - /opt/volumes/h2/:/opt/h2-data
    
#END